In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
Alliance_data = pd.read_csv("alliance_v4.1_by_directed_yearly.csv")

The above data comes from here: https://correlatesofwar.org/data-sets/formal-alliances/. It is a CSV containing data on alliances between countries from the 19th Century to the present. 
The purpose of this notebook is to create two specific CSV's:
1) A csv containing all countries the USA made a meaningful alliance with after the second-world war and maintained until at least 1970.
2) A csv containing all countries the USA had a meaningful alliance with after the second-world war and maintained until at least 1970. This includes countries that the USA allied with after the war or had made an alliance with previously.

The criteria for a "meaningful alliance" is as follows: defense OR nonaggression OR entente. The neutrality treaties seem to be much weaker agreements that don't last long, as a way to signal "ok we'll stop fighting

In [7]:
Alliance_data.head(5)

,version4id,ccode1,state_name1,ccode2,state_name2,dyad_st_day,dyad_st_month,dyad_st_year,dyad_end_day,dyad_end_month,dyad_end_year,left_censor,right_censor,defense,neutrality,nonaggression,entente,year,version
0,1,200,United Kingdom,235,Portugal,1,1,1816,NaN,NaN,2012.0,1,1,1,0,1.0,0.0,1816,4.1
1,1,200,United Kingdom,235,Portugal,1,1,1816,NaN,NaN,2012.0,1,1,1,0,1.0,0.0,1817,4.1
2,1,200,United Kingdom,235,Portugal,1,1,1816,NaN,NaN,2012.0,1,1,1,0,1.0,0.0,1818,4.1
3,1,200,United Kingdom,235,Portugal,1,1,1816,NaN,NaN,2012.0,1,1,1,0,1.0,0.0,1819,4.1
4,1,200,United Kingdom,235,Portugal,1,1,1816,NaN,NaN,2012.0,1,1,1,0,1.0,0.0,1820,4.1

In [9]:
#The data pertaining exclusively to American alliances may be extracted
US_alliance_data=Alliance_data[Alliance_data['state_name1'] == "United States of America"]
US_alliance_data.head(5)

,version4id,ccode1,state_name1,ccode2,state_name2,dyad_st_day,dyad_st_month,dyad_st_year,dyad_end_day,dyad_end_month,dyad_end_year,left_censor,right_censor,defense,neutrality,nonaggression,entente,year,version
7212,85,2,United States of America,740,Japan,30,11,1908,4.0,7.0,1910.0,0,0,0,0,0.0,1.0,1908,4.1
7213,85,2,United States of America,740,Japan,30,11,1908,4.0,7.0,1910.0,0,0,0,0,0.0,1.0,1909,4.1
7214,85,2,United States of America,740,Japan,30,11,1908,4.0,7.0,1910.0,0,0,0,0,0.0,1.0,1910,4.1
7958,111,2,United States of America,200,United Kingdom,13,12,1921,18.0,9.0,1931.0,0,0,0,0,0.0,1.0,1921,4.1
7959,111,2,United States of America,200,United Kingdom,13,12,1921,18.0,9.0,1931.0,0,0,0,0,0.0,1.0,1922,4.1

In [10]:
#to get some insight into contemporary American Foreign Policy it will be useful to look at years after 1945
US_alliance_data=US_alliance_data[US_alliance_data['dyad_st_year'] > 1945]
US_alliance_data.head(20)

,version4id,ccode1,state_name1,ccode2,state_name2,dyad_st_day,dyad_st_month,dyad_st_year,dyad_end_day,dyad_end_month,dyad_end_year,left_censor,right_censor,defense,neutrality,nonaggression,entente,year,version
35430,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,1989,4.1
35431,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,1990,4.1
35432,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,1991,4.1
35433,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,1992,4.1
35434,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,1993,4.1
35435,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,1994,4.1
35436,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,1995,4.1
35437,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,1996,4.1
35438,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,1997,4.1
35439,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,1998,4.1
35440,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,1999,4.1
35441,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,2000,4.1
35442,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,2001,4.1
35443,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,2002,4.1
35444,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,2003,4.1
35445,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,2004,4.1
35446,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,2005,4.1
35447,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,2006,4.1
35448,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,2007,4.1
35449,210,2,United States of America,20,Canada,13,11,1989,NaN,NaN,2012.0,0,1,1,0,1.0,1.0,2008,4.1

In [17]:
US_alliance_data[US_alliance_data['state_name2'] == "Iran"]

,version4id,ccode1,state_name1,ccode2,state_name2,dyad_st_day,dyad_st_month,dyad_st_year,dyad_end_day,dyad_end_month,dyad_end_year,left_censor,right_censor,defense,neutrality,nonaggression,entente,year,version
121712,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1958,4.1
121713,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1959,4.1
121714,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1960,4.1
121715,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1961,4.1
121716,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1962,4.1
121717,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1963,4.1
121718,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1964,4.1
121719,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1965,4.1
121720,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1966,4.1
121721,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1967,4.1
121722,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1968,4.1
121723,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1969,4.1
121724,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1970,4.1
121725,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1971,4.1
121726,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1972,4.1
121727,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1973,4.1
121728,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1974,4.1
121729,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1975,4.1
121730,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1976,4.1
121731,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1977,4.1
121732,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1978,4.1
121733,241,2,United States of America,630,Iran,28,7,1958,12.0,3.0,1979.0,0,0,0,0,1.0,1.0,1979,4.1
123868,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1959,4.1
123869,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1960,4.1
123870,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1961,4.1
123871,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1962,4.1
123872,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1963,4.1
123873,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1964,4.1
123874,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1965,4.1
123875,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1966,4.1
123876,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1967,4.1
123877,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1968,4.1
123878,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1969,4.1
123879,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1970,4.1
123880,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1971,4.1
123881,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1972,4.1
123882,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1973,4.1
123883,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1974,4.1
123884,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1975,4.1
123885,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1976,4.1
123886,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1977,4.1
123887,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1978,4.1
123888,253,2,United States of America,630,Iran,5,3,1959,11.0,2.0,1979.0,0,0,0,0,0.0,1.0,1979,4.1